use std::os::raw::c_char;

// Include Rust sources generated by bindgen.
// This include is conditional because SPDK bindings can only be built on
// Linux.
#[cfg(target_os = "linux")]
include!(concat!(env!("OUT_DIR"), "/libspdk.rs"));

// In order to IDE to work properly with SPDK definitions on non-Linux platform,
// one can copy generated bindings (libspdk.rs) from a Linux target and put them
// to .pregenerated directory.
// This has to be done every time SPDK is changed.
#[cfg(not(target_os = "linux"))]
include!("../../.pregenerated/libspdk.rs");
